ServerEvents.tags('item', e => {
    //food
	e.add('origins:meat', 'brewery:sausage')
	e.add('origins:meat', 'brewery:pork_knuckle')
	e.add('origins:meat', 'born_in_chaos_v1:bloody_gadfly_eye')
	e.add('origins:meat', 'born_in_chaos_v1:fried_maggot')
	e.add('origins:meat', 'born_in_chaos_v1:corpse_maggot')
	e.add('origins:meat', 'betterend:end_fish_raw')
	e.add('origins:meat', 'betterend:end_fish_cooked')
	e.add('origins:meat', 'brewery:fried_chicken')
	e.add('origins:meat', 'brewery:half_chicken')
    
	e.add('ico:partial_meat', 'farmersdelight:salmon_roll')
	e.add('ico:partial_meat', 'farmersdelight:cabbage_rolls')
	e.add('ico:partial_meat', 'farmersdelight:stuffed_potato')
	e.add('ico:partial_meat', 'farmersdelight:mutton_wrap')
	e.add('ico:partial_meat', 'farmersdelight:bacon_sandwich')
	e.add('ico:partial_meat', 'farmersdelight:hamburger')
	e.add('ico:partial_meat', 'farmersdelight:chicken_sandwich')
	e.add('ico:partial_meat', 'farmersdelight:egg_sandwich')
	e.add('ico:partial_meat', 'farmersdelight:barbecue_stick')
	e.add('ico:partial_meat', 'farmersdelight:cod_roll')
	e.add('ico:partial_meat', 'farmersdelight:steak_and_potatoes')
	e.add('ico:partial_meat', 'farmersdelight:roasted_mutton_chops')
	e.add('ico:partial_meat', 'farmersdelight:pasta_with_mutton_chop')
	e.add('ico:partial_meat', 'farmersdelight:pasta_with_meatballs')
	e.add('ico:partial_meat', 'farmersdelight:noodle_soup')
	e.add('ico:partial_meat', 'farmersdelight:baked_cod_stew')
	e.add('ico:partial_meat', 'farmersdelight:chicken_soup')
	e.add('ico:partial_meat', 'farmersdelight:beef_stew')
	e.add('ico:partial_meat', 'farmersdelight:fish_stew')
	e.add('ico:partial_meat', 'farmersdelight:roast_chicken')
	e.add('ico:partial_meat', 'farmersdelight:honey_glazed_ham')
	e.add('ico:partial_meat', 'farmersdelight:shepherds_pie')
	e.add('ico:partial_meat', 'farmersdelight:grilled_salmon')
	e.add('ico:partial_meat', 'farmersdelight:squid_ink_pasta')
	e.add('ico:partial_meat', 'pneumaticcraft:salmon_tempura')
})